//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public decimal SellingPrice { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> SOH { get; set; }
        public int SupplierID { get; set; }
    
        public virtual Category Category1 { get; set; }
    }
}
